package com.acl.print;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigInteger;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.naming.NamingException;

import org.apache.poi.wp.usermodel.HeaderFooterType;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFHeader;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;

import com.acl.bean.UserBean;
import com.acl.dao.EmployeesDao;

public class PrintToWord {
	private XWPFDocument document;

	public boolean printToWord(String limit, String offset, String username) throws NumberFormatException, NamingException, SQLException, IOException {
		document = new XWPFDocument();
		FileOutputStream out = null;
		ArrayList<UserBean> view = null;
		EmployeesDao ed = new EmployeesDao();
		String tableName = new SimpleDateFormat("dd-MM-yyyy_HH-mm-ss").format(new Date());
		String path = "D:/eclipse-workspace/accessControlLogins/print/" + tableName + ".docx";

		try {
			view = ed.getView(Integer.parseInt(limit), Integer.parseInt(offset));
			out = new FileOutputStream(new File(path));
			XWPFParagraph paragraph = document.createParagraph();
			XWPFRun run=paragraph.createRun();
			XWPFHeader header = document.createHeader(HeaderFooterType.FIRST);
			  
			run.setText("Report generated by: " + username + ", " + new Date());
			
			paragraph = header.createParagraph();
			paragraph.setAlignment(ParagraphAlignment.LEFT);
			run = paragraph.createRun();  
			run.setText("User Details");
			
			XWPFTable table = document.createTable();
			
			XWPFTableRow tableHead = table.getRow(0);
			tableHead.getCell(0).setText("user id");
			tableHead.addNewTableCell().setText("username");
			tableHead.addNewTableCell().setText("user role");
			tableHead.addNewTableCell().setText("email");
			tableHead.addNewTableCell().setText("phone");
			
			for(UserBean bean : view) {
				int count = 0;
				XWPFTableRow tableRows = table.createRow();
				tableRows.getCell(count++).setText(bean.getUserid().toString());
				tableRows.getCell(count++).setText(bean.getUsername().toString());
				tableRows.getCell(count++).setText(bean.getRole_name().toString());
				tableRows.getCell(count++).setText(bean.getEmail().toString());
				tableRows.getCell(count).setText(bean.getPhone().toString());
			}
			document.write(out);
			return true;
		} finally {
			if(out!=null) {
				out.close();
			}
		}
	}
}
